# Generated by Django 4.2.2 on 2023-06-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('time_connected', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_id', models.IntegerField()),
                ('time_packet_send', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorLight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_id', models.IntegerField()),
                ('sensor_id', models.IntegerField()),
                ('light', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorTemperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_id', models.IntegerField()),
                ('sensor_id', models.IntegerField()),
                ('temperature', models.FloatField(max_length=10)),
            ],
        ),
    ]
